### ISSUE TITLE
Tournament matches issues

### ISSUE THREAD

**Issue by hraki** [stoopkid1/ezleague#168] opened 2015-05-11 19:02 UTC
I found a issue when you try to report a result of a match.

The match is created the players can accept the match details, and it shows to submit the score, you submit the score and the other team only have the option to submit the score (Instead of the accept or dispute) they only have the Submit button.

On admin panel in the Edit Match it appears both players have accepted (but they only submit) and if I complete the match (in the admin panel) the only thing that changes is the players can submit the score (they can change it even if the match is finished) of dispute the result.

the matches are created on DataBase

And the last thing, there is any chance to have WildCards ? Because if you create a 8 players tournament (but you only have 7players) you can't start the tournament

**Comment by stoopkid1** [comment] 2015-05-12 03:12
@hraki scores can only be submitted once both teams have accepted the match details. once the match details have been accepted, then either team can submit the match score. it's not possible to submit a score if only 1 team has accepted the match details.

i'll modify the "match completion" functionality, but everything else is working as it was intended too. 

there will not be an option for "wildcards". if you are short on teams/players for a tournament, you can create a few fake/dummy teams, and add them to the tournament. once you're able to generate the round 1 matches, you can edit the match(s) so the fake/dummy team loses.

**Comment by stoopkid1** [comment] 2015-05-12 05:25
@hraki some new functionality introduced based on your request. view the details here https://github.com/stoopkid1/ezleague/pull/169

**Comment by hraki** [comment] 2015-05-12 18:21
Thanks for the fix!

On the tournament matches the admin have to manually set match complete correct?

**Comment by stoopkid1** [comment] 2015-05-13 02:52
@hraki if an admin modifies the match, it will be marked as completed when the score gets entered (new feature). if the admin resets the score to 0-0, it will re-open the status.

i'll look into adding tournament matches to "recent matches" on the sidebar. 

make sure you run the database upgrade from the Admin panel. if you're missing `admin/upgrade.php`, re-download it, because new tables were created for the tournament disputes

**Comment by stoopkid1** [comment] 2015-06-21 01:14
closing.

**Closed by stoopkid1** 2015-06-21 01:14 UTC
